version: '3.1'

services:

  broker-api:
    container_name: broker-api
    image: broker-web-api
    build:
      context: .
      dockerfile: Broker.Api/Dockerfile
    ports:
      - 8080:80
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
  mongo:
    image: mongo
    ports:
      - 27017:27017
  broker-consumer:
    container_name: broker-app
    image: broker-consumer-app
    build:
      context: .
      dockerfile: Broker.Consumer/Dockerfile